# Generated by Django 3.1.3 on 2020-11-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Frances'), ('de', 'German'), ('uk', 'Ukrainian')], max_length=2)),
            ],
        ),
    ]
